modLoader="javafml"
loaderVersion="${fml_version_range}"
license="MIT"
[[mods]]
modId="tfcatlas"
version="${mod_version}"
displayName="TFC Atlas"
authors="RYAN S"
displayTest="IGNORE_ALL_VERSION"
description='''See unexplored TFC terrain on Xaero's World Map and search for a place to build.'''
[[dependencies.tfcatlas]]
modId="neoforge"
type="required"
versionRange="${loader_version_range}"
ordering="NONE"
side="CLIENT"
[[dependencies.tfcatlas]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
[[dependencies.tfcatlas]]
modId="tfc"
type="required"
versionRange="${tfc_version_range}"
ordering="AFTER"
side="CLIENT"
[[dependencies.tfcatlas]]
modId="xaeroworldmap"
type="required"
versionRange="${xaero_version_range}"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="tfcatlas.mixins.json"
