tfc\:rock/raw/limestone=887f6b
tfc\:rock/raw/granite=55464a
tfc\:rock/raw/chert=7a4e46
tfc\:rock/raw/rhyolite=736267
tfc\:rock/raw/gabbro=5d5544
tfc\:rock/raw/conglomerate=6f7165
tfc\:rock/raw/slate=7d7467
tfc\:rock/raw/shale=464346
tfc\:rock/raw/dacite=7a7b7b
tfc\:rock/raw/chalk=c7c7c1
tfc\:rock/raw/andesite=606060
tfc\:rock/raw/marble=e3ebeb
tfc\:rock/raw/claystone=8d6644
tfc\:rock/raw/phyllite=949da9
tfc\:rock/raw/gneiss=736d60
tfc\:rock/raw/dolomite=3c4659
tfc\:rock/raw/quartzite=8c8180
tfc\:rock/raw/schist=4d5441
tfc\:rock/raw/diorite=8e8e8e
tfc\:rock/raw/basalt=1d2021
tfc\:river=00c8ff
tfc\:mountains=ff3232
tfc\:low_canyons=c86eff
tfc\:old_mountain_lake=b4b4ff
tfc\:badlands=ff9600
tfc\:inverted_badlands=f09600
tfc\:oceanic_mountain_lake=b4b4ff
tfc\:ocean_reef=46a0fa
tfc\:volcanic_mountain_lake=b4b4ff
tfc\:plateau_lake=b4b4ff
tfc\:plateau=d27878
tfc\:lowlands=dc96e6
tfc\:plains=64c864
tfc\:canyons=b43cff
tfc\:volcanic_oceanic_mountains=ff00ff
tfc\:deep_ocean=0000a0
tfc\:hills=508250
tfc\:deep_ocean_trench=000050
tfc\:mountain_lake=b4b4ff
tfc\:volcanic_mountains=ff3232
tfc\:oceanic_mountains=ff00ff
tfc\:volcanic_oceanic_mountain_lake=b4b4ff
tfc\:shore=e6d282
tfc\:salt_marsh=4d2727
tfc\:lake=1e1eff
tfc\:highlands=14501e
tfc\:tidal_flats=a0ad6a
tfc\:rolling_hills=326432
tfc\:ocean=0000dc
tfc\:old_mountains=f06464
