tfc\:rock/raw/limestone=887f6b
tfc\:rock/raw/granite=55464a
tfc\:rock/raw/chert=7a4e46
tfc\:rock/raw/rhyolite=736267
tfc\:rock/raw/gabbro=5d5544
tfc\:rock/raw/conglomerate=6f7165
tfc\:rock/raw/slate=7d7467
tfc\:rock/raw/shale=464346
tfc\:rock/raw/dacite=7a7b7b
tfc\:rock/raw/chalk=c7c7c1
tfc\:rock/raw/andesite=606060
tfc\:rock/raw/marble=e3ebeb
tfc\:rock/raw/claystone=8d6644
tfc\:rock/raw/phyllite=949da9
tfc\:rock/raw/gneiss=736d60
tfc\:rock/raw/dolomite=3c4659
tfc\:rock/raw/quartzite=8c8180
tfc\:rock/raw/schist=4d5441
tfc\:rock/raw/diorite=8e8e8e
tfc\:rock/raw/basalt=1d2021
tfc\:river=00c8ff
tfc\:mountains=ff3232
tfc\:low_canyons=c86eff
tfc\:old_mountain_lake=b4b4ff
tfc\:badlands=ff9600
tfc\:oceanic_mountain_lake=b4b4ff
tfc\:ocean_reef=46a0fa
tfc\:volcanic_mountain_lake=b4b4ff
tfc\:plateau_lake=b4b4ff
tfc\:plateau=d27878
tfc\:lowlands=dc96e6
tfc\:plains=64c864
tfc\:canyons=b43cff
tfc\:volcanic_oceanic_mountains=ff00ff
tfc\:deep_ocean=0000a0
tfc\:hills=508250
tfc\:deep_ocean_trench=000050
tfc\:mountain_lake=b4b4ff
tfc\:volcanic_mountains=ff3232
tfc\:oceanic_mountains=ff00ff
tfc\:volcanic_oceanic_mountain_lake=b4b4ff
tfc\:shore=e6d282
tfc\:salt_marsh=4d2727
tfc\:lake=1e1eff
tfc\:highlands=14501e
tfc\:tidal_flats=a0ad6a
tfc\:rolling_hills=326432
tfc\:ocean=0000dc
tfc\:old_mountains=f06464
tfc\:active_shield_volcano=804D97
tfc\:ancient_shield_volcano=0072B2
tfc\:burren_badlands=6EA548
tfc\:burren_badlands_tall=C5B37E
tfc\:burren_plains=CC79A7
tfc\:burren_plateau=804D97
tfc\:burren_roche_moutonee=D8888A
tfc\:buttes=D8888A
tfc\:cenote_canyons=D55E00
tfc\:cenote_highlands=0072B2
tfc\:cenote_hills=0072B2
tfc\:cenote_plains=CC79A7
tfc\:cenote_plateau=804D97
tfc\:cenote_rolling_hills=D8888A
tfc\:coastal_dunes=56B4E9
tfc\:collisional_mountains=AAB8BA
tfc\:deep_ocean_atolls=F0E442
tfc\:doline_canyons=0072B2
tfc\:doline_highlands=C5B37E
tfc\:doline_hills=AAB8BA
tfc\:doline_plains=0072B2
tfc\:doline_plateau=CC79A7
tfc\:doline_rolling_hills=6EA548
tfc\:dormant_shield_volcano=C5B37E
tfc\:drumlins=D55E00
tfc\:dune_sea=D55E00
tfc\:embayments=804D97
tfc\:extinct_shield_volcano=6EA548
tfc\:extreme_doline_mountains=009E73
tfc\:extreme_doline_plateau=D8888A
tfc\:glacially_carved_mountains=F0E442
tfc\:glacially_carved_oceanic_mountains=CC79A7
tfc\:glacially_carved_volcanic_mountains=F0E442
tfc\:glacially_carved_volcanic_oceanic_mountains=C5B37E
tfc\:glaciated_mountains=D8888A
tfc\:glaciated_oceanic_mountains=CC79A7
tfc\:glaciated_shield_volcano=0072B2
tfc\:glaciated_volcanic_mountains=F0E442
tfc\:glaciated_volcanic_oceanic_mountains=CC79A7
tfc\:grassy_dunes=804D97
tfc\:guano_island=D55E00
tfc\:hoodoos=D8888A
tfc\:ice_sheet=D8888A
tfc\:ice_sheet_edge=D8888A
tfc\:ice_sheet_mountains=6EA548
tfc\:ice_sheet_mountains_edge=CC79A7
tfc\:ice_sheet_oceanic=C5B37E
tfc\:ice_sheet_oceanic_mountains=F0E442
tfc\:ice_sheet_oceanic_mountains_edge=D8888A
tfc\:ice_sheet_shield_volcano=6EA548
tfc\:ice_sheet_shore=56B4E9
tfc\:ice_sheet_tuyas=E69F00
tfc\:ice_sheet_tuyas_edge=CC79A7
tfc\:ice_sheet_volcanic_mountains=CC79A7
tfc\:ice_sheet_volcanic_oceanic_mountains=0072B2
tfc\:inverted_patterned_ground=0072B2
tfc\:knob_and_kettle=AAB8BA
tfc\:meltwater_lake=804D97
tfc\:mesas=0072B2
tfc\:mud_flats=009E73
tfc\:ocean_atolls=6EA548
tfc\:ocean_ridge=D55E00
tfc\:oceanic_volcanic_arc=D8888A
tfc\:old_shield_volcano_shore=C5B37E
tfc\:patterned_ground=56B4E9
tfc\:plateau_wide=E69F00
tfc\:rift_lake=56B4E9
tfc\:rift_valley=804D97
tfc\:river_valley=AAB8BA
tfc\:rocky_plateau=D8888A
tfc\:rocky_shores=D8888A
tfc\:salt_flats=F0E442
tfc\:sea_stacks=0072B2
tfc\:setback_cliffs=009E73
tfc\:shield_volcano_shore=CC79A7
tfc\:shilin_canyons=009E73
tfc\:shilin_highlands=D55E00
tfc\:shilin_hills=E69F00
tfc\:shilin_plains=F0E442
tfc\:shilin_plateau=6EA548
tfc\:stair_step_canyons=C5B37E
tfc\:stone_circles=56B4E9
tfc\:subglacial_lake=804D97
tfc\:sunken_shield_volcano=F0E442
tfc\:terrace_lower=CC79A7
tfc\:terrace_upper=0072B2
tfc\:tower_karst_bay=E69F00
tfc\:tower_karst_canyons=F0E442
tfc\:tower_karst_highlands=6EA548
tfc\:tower_karst_hills=D55E00
tfc\:tower_karst_lake=804D97
tfc\:tower_karst_plains=D8888A
tfc\:tuyas=D55E00
tfc\:volcanic_island=56B4E9
tfc\:volcanic_mountain_islands=C5B37E
tfc\:whorled_canyons=F0E442
